module ProfilesHelper
  def denominations
    [
      ['Other: Not Listed', 'Other'],
      ['Undeclared', 'Undeclared'],
      ['Anglican', 'Anglican'],
      ['Apostolic Christian', 'Apostolic Christian'],
      ['Apostolic Faith', 'Apostolic Faith'],
      ['Assembly of God', 'Assembly of God'],
      ['Baptist-Other', 'Baptist-Other'],
      ['Bible', 'Bible'],
      ['Brethren', 'Brethren'],
      ['Catholic', 'Catholic'],
      ['Charismatic', 'Charismatic'],
      ['Christian', 'Christian'],
      ['Church of Christ', 'Church of Christ'],
      ['Church of God', 'Church of God'],
      ['Congregational', 'Congregational'],
      ['Covenant', 'Covenant'],
      ['Disciples of Christ', 'Disciples of Christ'],
      ['Eastern Orthodox', 'Eastern Orthodox'],
      ['Ecumenical', 'Ecumenical'],
      ['Episcopal', 'Episcopal'],
      ['Evangelical Free', 'Evangelical Free'],
      ['Four Square Gospel', 'Four Square Gospel'],
      ['Free Methodist', 'Free Methodist'],
      ['Friends (Quaker)', 'Friends (Quaker)'],
      ['Full Gospel', 'Full Gospel'],
      ['Interdenominational', 'Interdenominational'],
      ['Jewish', 'Jewish'],
      ['Lutheran', 'Lutheran'],
      ['Mennonite', 'Mennonite'],
      ['Messianic Jew', 'Messianic Jew'],
      ['Methodist', 'Methodist'],
      ['Nazarene', 'Nazarene'],
      ['Non-denominational', 'Non-denominational'],
      ['Pentecostal', 'Pentecostal'],
      ['Presbyterian', 'Presbyterian'],
      ['Protestant', 'Protestant'],
      ['Seventh Day Adventist', 'Seventh Day Adventist'],
      ['Southern Baptist', 'Southern Baptist'],
      ['United Brethren', 'United Brethren'],
      ['Wesleyan', 'Wesleyan']
    ]
  end
  
  def languages
    [
      ['English', 'English'],
      ['French', 'French'],
      ['Italian', 'Italian'],
      ['German', 'German'],
      ['Spanish', 'Spanish'],
      ['Other', 'Other'],
      ['Arabic', 'Arabic'],
      ['Bengali', 'Bengali'],
      ['Chinese', 'Chinese'],
      ['Hindi', 'Hindi'],
      ['Japanese', 'Japanese'],
      ['Javanese', 'Javanese'],
      ['Korean', 'Korean'],
      ['Lahnda', 'Lahnda'],
      ['Mandarin', 'Mandarin'],
      ['Marathi', 'Marathi'],
      ['Portuguese', 'Portuguese'],
      ['Russian', 'Russian'],
      ['Tamil', 'Tamil'],
      ['Telugu', 'Telugu'],
      ['Turkish', 'Turkish'],
      ['Urdu', 'Urdu'],
      ['Vietnamese', 'Vietnamese']
    ]
  end

  def military_statuses
    [
      ['N/A', 'N/A'],
      ['Active', 'Active'],
      ['Reserve', 'Reserve'],
      ['Veteran', 'Veteran'],
      ['Spouse', 'Spouse'],
      ['Retired', 'Retired'],
      ['DOD Employee', 'DOD Employee'],
      ['Dependent', 'Dependent']
    ]
  end

  def marital_statuses
    [
      ['Decline to Answer', 'Decline to Answer'],
      ['Single', 'Single'],
      ['Married', 'Married'],
      ['Separated', 'Separated'],
      ['Divorced', 'Divorced'],
      ['Widowed', 'Widowed'],
      ['Other: Not Listed', 'Other'],
    ]
  end

  def referral_source
    [
      ['LinkedIn','LinkedIn'],
      ['Facebook','Facebook'],
      ['Indeed','Indeed'],
      ['ADP','ADP'],
      ['University Job Board','University'],
      ['Seminary Job Board','Seminary'],
      ['Church Job Board','Church'],
      ['Word of Mouth','Word of Mouth']
    ]
  end

  def us_states
    [
      ['AL - Alabama', 'AL'],
      ['AK - Alaska', 'AK'],
      ['AZ - Arizona', 'AZ'],
      ['AR - Arkansas', 'AR'],
      ['CA - California', 'CA'],
      ['CO - Colorado', 'CO'],
      ['CT - Connecticut', 'CT'],
      ['DE - Delaware', 'DE'],
      ['DC - District of Columbia', 'DC'],
      ['FL - Florida', 'FL'],
      ['GA - Georgia', 'GA'],
      ['HI - Hawaii', 'HI'],
      ['ID - Idaho', 'ID'],
      ['IL - Illinois', 'IL'],
      ['IN - Indiana', 'IN'],
      ['IA - Iowa', 'IA'],
      ['KS - Kansas', 'KS'],
      ['KY - Kentucky', 'KY'],
      ['LA - Louisiana', 'LA'],
      ['ME - Maine', 'ME'],
      ['MD - Maryland', 'MD'],
      ['MA - Massachusetts', 'MA'],
      ['MI - Michigan', 'MI'],
      ['MN - Minnesota', 'MN'],
      ['MS - Mississippi', 'MS'],
      ['MO - Missouri', 'MO'],
      ['MT - Montana', 'MT'],
      ['NE - Nebraska', 'NE'],
      ['NV - Nevada', 'NV'],
      ['NH - New Hampshire', 'NH'],
      ['NJ - New Jersey', 'NJ'],
      ['NM - New Mexico', 'NM'],
      ['NY - New York', 'NY'],
      ['NC - North Carolina', 'NC'],
      ['ND - North Dakota', 'ND'],
      ['OH - Ohio', 'OH'],
      ['OK - Oklahoma', 'OK'],
      ['OR - Oregon', 'OR'],
      ['PA - Pennsylvania', 'PA'],
      ['PR - Puerto Rico', 'PR'],
      ['RI - Rhode Island', 'RI'],
      ['SC - South Carolina', 'SC'],
      ['SD - South Dakota', 'SD'],
      ['TN - Tennessee', 'TN'],
      ['TX - Texas', 'TX'],
      ['UT - Utah', 'UT'],
      ['VT - Vermont', 'VT'],
      ['VA - Virginia', 'VA'],
      ['WA - Washington', 'WA'],
      ['WV - West Virginia', 'WV'],
      ['WI - Wisconsin', 'WI'],
      ['WY - Wyoming', 'WY']
    ]
  end

  def countries
    [
      ['United States', 'United States'],
      ['Afghanistan', 'Afghanistan'],
      ['Aland Islands', 'Aland Islands'],
      ['Albania', 'Albania'],
      ['Algeria', 'Algeria'],
      ['American Samoa', 'American Samoa'],
      ['Andorra', 'Andorra'],
      ['Angola', 'Angola'],
      ['Anguilla', 'Anguilla'],
      ['Antarctica', 'Antarctica'],
      ['Antigua and Barbuda', 'Antigua and Barbuda'],
      ['Argentina', 'Argentina'],
      ['Armenia', 'Armenia'],
      ['Aruba ', 'Aruba '],
      ['Australia', 'Australia'],
      ['Austria', 'Austria'],
      ['Azerbaijan', 'Azerbaijan'],
      ['Bahamas', 'Bahamas'],
      ['Bahrain', 'Bahrain'],
      ['Bangladesh', 'Bangladesh'],
      ['Barbados', 'Barbados'],
      ['Belarus', 'Belarus'],
      ['Belgium', 'Belgium'],
      ['Belize', 'Belize'],
      ['Benin', 'Benin'],
      ['Bermuda', 'Bermuda'],
      ['Bhutan', 'Bhutan'],
      ['Bolivia', 'Bolivia'],
      ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'],
      ['Botswana', 'Botswana'],
      ['Bouvet Island', 'Bouvet Island'],
      ['Brazil', 'Brazil'],
      ['British Indian Ocean Territory', 'British Indian Ocean Territory'],
      ['Brunei Darussalam', 'Brunei Darussalam'],
      ['Bulgaria', 'Bulgaria'],
      ['Burkina Faso', 'Burkina Faso'],
      ['Burundi', 'Burundi'],
      ['Cambodia', 'Cambodia'],
      ['Cameroon', 'Cameroon'],
      ['Canada', 'Canada'],
      ['Cape Verde', 'Cape Verde'],
      ['Cayman Islands', 'Cayman Islands'],
      ['Central African Republic', 'Central African Republic'],
      ['Chad', 'Chad'],
      ['Chile', 'Chile'],
      ['China', 'China'],
      ['Christmas Island', 'Christmas Island'],
      ['Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'],
      ['Colombia', 'Colombia'],
      ['Comoros', 'Comoros'],
      ['Congo', 'Congo'],
      ['Congo, the Democratic Republic', 'Congo, the Democratic Republic'],
      ['Cook Islands', 'Cook Islands'],
      ['Costa Rica', 'Costa Rica'],
      ['Cote DIvoire (Ivory Coast)', 'Cote DIvoire (Ivory Coast)'],
      ['Croatia', 'Croatia'],
      ['Cuba', 'Cuba'],
      ['Cyprus', 'Cyprus'],
      ['Czech Republic', 'Czech Republic'],
      ['Democratic Yemen/Yemen', 'Democratic Yemen/Yemen'],
      ['Denmark', 'Denmark'],
      ['Djibouti', 'Djibouti'],
      ['Dominica', 'Dominica'],
      ['Dominican Republic', 'Dominican Republic'],
      ['Ecuador', 'Ecuador'],
      ['Egypt', 'Egypt'],
      ['El Salvador', 'El Salvador'],
      ['Equatorial Guinea', 'Equatorial Guinea'],
      ['Eritrea', 'Eritrea'],
      ['Estonia', 'Estonia'],
      ['Ethiopia', 'Ethiopia'],
      ['Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'],
      ['Faroe Islands', 'Faroe Islands'],
      ['Federated States of Micronesia', 'Federated States of Micronesia'],
      ['Fiji', 'Fiji'],
      ['Finland', 'Finland'],
      ['France', 'France'],
      ['French Guiana', 'French Guiana'],
      ['French Polynesia', 'French Polynesia'],
      ['French Southern Territories', 'French Southern Territories'],
      ['Gabon', 'Gabon'],
      ['Gambia', 'Gambia'],
      ['Georgia', 'Georgia'],
      ['Germany', 'Germany'],
      ['Ghana', 'Ghana'],
      ['Gibraltar', 'Gibraltar'],
      ['Greece', 'Greece'],
      ['Greenland', 'Greenland'],
      ['Grenada', 'Grenada'],
      ['Guadeloupe', 'Guadeloupe'],
      ['Guam', 'Guam'],
      ['Guatemala', 'Guatemala'],
      ['Guinea', 'Guinea'],
      ['Guinea-Bissau', 'Guinea-Bissau'],
      ['Guyana', 'Guyana'],
      ['Haiti', 'Haiti'],
      ['Heard and McDonald Islands', 'Heard and McDonald Islands'],
      ['Holy See (Vatican City State)', 'Holy See (Vatican City State)'],
      ['Honduras', 'Honduras'],
      ['Hong Kong', 'Hong Kong'],
      ['Hungary', 'Hungary'],
      ['Iceland', 'Iceland'],
      ['India', 'India'],
      ['Indonesia', 'Indonesia'],
      ['Iran, Islamic Republic of', 'Iran, Islamic Republic of'],
      ['Iraq', 'Iraq'],
      ['Ireland', 'Ireland'],
      ['4e72-e211-98d0-005056bb7df7">Isle of Man', '4e72-e211-98d0-005056bb7df7">Isle of Man'],
      ['Israel', 'Israel'],
      ['Italy', 'Italy'],
      ['Jamaica', 'Jamaica'],
      ['Japan', 'Japan'],
      ['Jordan', 'Jordan'],
      ['Kazakhstan', 'Kazakhstan'],
      ['Kenya', 'Kenya'],
      ['Kiribati', 'Kiribati'],
      ['Korea, Democratic People&#39;s Rep', 'Korea, Democratic People&#39;s Rep'],
      ['Korea, Republic of', 'Korea, Republic of'],
      ['2053-e511-8398-005056bb6ba2">Kosovo', '2053-e511-8398-005056bb6ba2">Kosovo'],
      ['Kuwait', 'Kuwait'],
      ['Kyrgyzstan', 'Kyrgyzstan'],
      ['Lao People&#39;s Democratic Republ', 'Lao People&#39;s Democratic Republ'],
      ['Latvia', 'Latvia'],
      ['Lebanon', 'Lebanon'],
      ['Lesotho', 'Lesotho'],
      ['Liberia', 'Liberia'],
      ['Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya'],
      ['Liechtenstein', 'Liechtenstein'],
      ['Lithuania', 'Lithuania'],
      ['Luxembourg', 'Luxembourg'],
      ['Macao', 'Macao'],
      ['Macedonia, Former Yugoslav Re', 'Macedonia, Former Yugoslav Re'],
      ['Madagascar', 'Madagascar'],
      ['Malawi', 'Malawi'],
      ['Malaysia', 'Malaysia'],
      ['Maldives', 'Maldives'],
      ['Mali', 'Mali'],
      ['Malta', 'Malta'],
      ['Marshall Islands', 'Marshall Islands'],
      ['Martinique', 'Martinique'],
      ['Mauritania', 'Mauritania'],
      ['Mauritius', 'Mauritius'],
      ['Mayotte', 'Mayotte'],
      ['Mexico', 'Mexico'],
      ['Moldova, Republic of', 'Moldova, Republic of'],
      ['Monaco', 'Monaco'],
      ['Mongolia', 'Mongolia'],
      ['aba4-df11-9faf-00219b8da3c7">Montenegro', 'aba4-df11-9faf-00219b8da3c7">Montenegro'],
      ['Montserrat', 'Montserrat'],
      ['Morocco', 'Morocco'],
      ['Mozambique', 'Mozambique'],
      ['Myanmar (Burma)', 'Myanmar (Burma)'],
      ['Namibia', 'Namibia'],
      ['Nauru', 'Nauru'],
      ['Nepal', 'Nepal'],
      ['Netherlands', 'Netherlands'],
      ['Netherlands Antilles', 'Netherlands Antilles'],
      ['New Caledonia', 'New Caledonia'],
      ['New Zealand', 'New Zealand'],
      ['Nicaragua', 'Nicaragua'],
      ['Niger', 'Niger'],
      ['Nigeria', 'Nigeria'],
      ['Niue', 'Niue'],
      ['Norfolk Island', 'Norfolk Island'],
      ['Northern Mariana Islands', 'Northern Mariana Islands'],
      ['Norway', 'Norway'],
      ['Oman', 'Oman'],
      ['63e8-db11-b552-00188b4ef3f8">Other', '63e8-db11-b552-00188b4ef3f8">Other'],
      ['Pakistan', 'Pakistan'],
      ['Palau', 'Palau'],
      ['Palestinian Territory, Occupie', 'Palestinian Territory, Occupie'],
      ['Panama', 'Panama'],
      ['Papua New Guinea', 'Papua New Guinea'],
      ['Paraguay', 'Paraguay'],
      ['Peru', 'Peru'],
      ['Philippines', 'Philippines'],
      ['Pitcairn', 'Pitcairn'],
      ['Poland', 'Poland'],
      ['Portugal', 'Portugal'],
      ['Puerto Rico', 'Puerto Rico'],
      ['Qatar', 'Qatar'],
      ['Reunion', 'Reunion'],
      ['Romania', 'Romania'],
      ['Russian Federation', 'Russian Federation'],
      ['Rwanda', 'Rwanda'],
      ['Saint Helena', 'Saint Helena'],
      ['Saint Kitts and Nevis', 'Saint Kitts and Nevis'],
      ['Saint Lucia', 'Saint Lucia'],
      ['Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'],
      ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'],
      ['Samoa', 'Samoa'],
      ['San Marino', 'San Marino'],
      ['Sao Tome and Principe', 'Sao Tome and Principe'],
      ['Saudi Arabia', 'Saudi Arabia'],
      ['Senegal', 'Senegal'],
      ['aba4-df11-9faf-00219b8da3c7">Serbia', 'aba4-df11-9faf-00219b8da3c7">Serbia'],
      ['Seychelles', 'Seychelles'],
      ['Sierra Leone', 'Sierra Leone'],
      ['Singapore', 'Singapore'],
      ['Slovakia', 'Slovakia'],
      ['Slovenia', 'Slovenia'],
      ['Solomon Islands', 'Solomon Islands'],
      ['Somalia', 'Somalia'],
      ['South Africa', 'South Africa'],
      ['South Georgia and the South Sa', 'South Georgia and the South Sa'],
      ['Spain', 'Spain'],
      ['Sri Lanka', 'Sri Lanka'],
      ['Sudan', 'Sudan'],
      ['Suriname', 'Suriname'],
      ['Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'],
      ['Swaziland', 'Swaziland'],
      ['Sweden', 'Sweden'],
      ['Switzerland', 'Switzerland'],
      ['Syrian Arab Republic', 'Syrian Arab Republic'],
      ['Taiwan, Province of China', 'Taiwan, Province of China'],
      ['Tajikistan', 'Tajikistan'],
      ['Tanzania, United Republic of', 'Tanzania, United Republic of'],
      ['Thailand', 'Thailand'],
      ['Timor-Leste', 'Timor-Leste'],
      ['Togo', 'Togo'],
      ['Tokelau', 'Tokelau'],
      ['Tonga', 'Tonga'],
      ['Trinidad and Tobago', 'Trinidad and Tobago'],
      ['Tunisia', 'Tunisia'],
      ['Turkey', 'Turkey'],
      ['Turkmenistan', 'Turkmenistan'],
      ['Turks and Caicos Islands', 'Turks and Caicos Islands'],
      ['Tuvalu', 'Tuvalu'],
      ['Uganda', 'Uganda'],
      ['Ukraine', 'Ukraine'],
      ['United Arab Emirates', 'United Arab Emirates'],
      ['United Kingdom (Great Britain)', 'United Kingdom (Great Britain)'],
      ['Uruguay', 'Uruguay'],
      ['Uzbekistan', 'Uzbekistan'],
      ['Vanuatu', 'Vanuatu'],
      ['Venezuela', 'Venezuela'],
      ['Vietnam', 'Vietnam'],
      ['Virgin Islands, British', 'Virgin Islands, British'],
      ['Virgin Islands, U.S.', 'Virgin Islands, U.S.'],
      ['Wallis and Futuna', 'Wallis and Futuna'],
      ['Western Sahara', 'Western Sahara'],
      ['Zambia', 'Zambia'],
      ['Zimbabw', 'Zimbabwe']
    ]
  end

  def native_tribes
    [
      ['Decline to Answer', 'Decline to Answer'],
      ['Not Applicable', 'Not Applicable'],
      ['Grand Portage Band:', 'Grand Portage Band:'],
      ['Absentee-Shawnee Tribe', 'Absentee-Shawnee Tribe'],
      ['Afognak Native Corporation', 'Afognak Native Corporation'],
      ['Agdaagux Tribe of King Cove', 'Agdaagux Tribe of King Cove'],
      ['Agua Caliente Band of Cahuilla', 'Agua Caliente Band of Cahuilla'],
      ['Ak Chin Indian Community', 'Ak Chin Indian Community'],
      ['Akiachak Native Community', 'Akiachak Native Community'],
      ['Akiak Native Community', 'Akiak Native Community'],
      ['Alabama and Coushatta Tribes', 'Alabama and Coushatta Tribes'],
      ['Alabama-Quassarte Tribal', 'Alabama-Quassarte Tribal'],
      ['Alaskan Native', 'Alaskan Native'],
      ['Alatna Village', 'Alatna Village'],
      ['Algaaciq Native Village (St. Mary&#39;s)', 'Algaaciq Native Village (St. Mary&#39;s)'],
      ['Allakaket Village', 'Allakaket Village'],
      ['Alturas Indian', 'Alturas Indian'],
      ['Angoon Community Association', 'Angoon Community Association'],
      ['Annette Island Reserve', 'Annette Island Reserve'],
      ['Anvik Village', 'Anvik Village'],
      ['Apache Tribe of Oklahoma', 'Apache Tribe of Oklahoma'],
      ['Arapahoe Tribe', 'Arapahoe Tribe'],
      ['Arctic Village (See Native Village Venetie Tribal Government)', 'Arctic Village (See Native Village Venetie Tribal Government)'],
      ['Aroostook Band of Micmac Indians', 'Aroostook Band of Micmac Indians'],
      ['Assiniboine and Sioux Tribes', 'Assiniboine and Sioux Tribes'],
      ['Atqasuk Village (Atkasook)', 'Atqasuk Village (Atkasook)'],
      ['Augustine Band of Cahuilla Mission', 'Augustine Band of Cahuilla Mission'],
      ['Bad River Band of the Lake Superior', 'Bad River Band of the Lake Superior'],
      ['Barona Group of Capitan Grande', 'Barona Group of Capitan Grande'],
      ['Bay Mills Indian Community', 'Bay Mills Indian Community'],
      ['Bear River Band', 'Bear River Band'],
      ['Beaver Village', 'Beaver Village'],
      ['Berry Creek Rancheria of Maidu', 'Berry Creek Rancheria of Maidu'],
      ['Big Lagoon Rancheria of Smith River', 'Big Lagoon Rancheria of Smith River'],
      ['Big Pine Band of Owens Valley Paiute Shoshone', 'Big Pine Band of Owens Valley Paiute Shoshone'],
      ['Big Sandy Rancheria of Mono Indians', 'Big Sandy Rancheria of Mono Indians'],
      ['Big Valley Rancheria of Pomo &amp; Pit River Indians', 'Big Valley Rancheria of Pomo &amp; Pit River Indians'],
      ['Birch Creek Village', 'Birch Creek Village'],
      ['Bishop Paiute Tribe', 'Bishop Paiute Tribe'],
      ['Blackfeet Tribe', 'Blackfeet Tribe'],
      ['Buena Vista Rancheria of Me-Wuk Indians', 'Buena Vista Rancheria of Me-Wuk Indians'],
      ['Burns Paiute Tribe of the Burns Paiute Indian', 'Burns Paiute Tribe of the Burns Paiute Indian'],
      ['Cabazon Band of Cahuilla Mission Indians', 'Cabazon Band of Cahuilla Mission Indians'],
      ['Cachil DeHe Band of Wintun Indians', 'Cachil DeHe Band of Wintun Indians'],
      ['Caddo Indian Tribe of Oklahoma', 'Caddo Indian Tribe of Oklahoma'],
      ['Cahto Indian Tribe', 'Cahto Indian Tribe'],
      ['Cahuilla Band of Mission Indians', 'Cahuilla Band of Mission Indians'],
      ['California Bridgeport Paiute Indian', 'California Bridgeport Paiute Indian'],
      ['California Ione Band of Miwok Indians of California', 'California Ione Band of Miwok Indians of California'],
      ['Campo Band of Diegueno Mission Indians', 'Campo Band of Diegueno Mission Indians'],
      ['Capitan Grande Band of Diegueno Mission Indians', 'Capitan Grande Band of Diegueno Mission Indians'],
      ['Carry the Kettle Nakota First Nation Canada', 'Carry the Kettle Nakota First Nation Canada'],
      ['Catawba Tribe', 'Catawba Tribe'],
      ['Cayuga Nation', 'Cayuga Nation'],
      ['Cedarville Rancheria of Northern Paiute Indians', 'Cedarville Rancheria of Northern Paiute Indians'],
      ['Central Council of the Tlingit &amp; Haida Indian Tribes', 'Central Council of the Tlingit &amp; Haida Indian Tribes'],
      ['Chalkyitsik Village', 'Chalkyitsik Village'],
      ['Chemehuevi Indian Tribe', 'Chemehuevi Indian Tribe'],
      ['Cher-Ae Heights Indian Community', 'Cher-Ae Heights Indian Community'],
      ['Cherokee Nation of Oklahoma', 'Cherokee Nation of Oklahoma'],
      ['Chevak Native Village', 'Chevak Native Village'],
      ['Cheyenne River Sioux Tribe', 'Cheyenne River Sioux Tribe'],
      ['Cheyenne-Arapaho Tribes', 'Cheyenne-Arapaho Tribes'],
      ['Chickaloon Native Village', 'Chickaloon Native Village'],
      ['Chickasaw Nation of Oklahoma', 'Chickasaw Nation of Oklahoma'],
      ['Chicken Ranch Rancheria of Me-Wuk Indians', 'Chicken Ranch Rancheria of Me-Wuk Indians'],
      ['Chignik Lake Village', 'Chignik Lake Village'],
      ['Chilkat Indian Village (Kluckwan)', 'Chilkat Indian Village (Kluckwan)'],
      ['Chilkoot Indian Association (Haines)', 'Chilkoot Indian Association (Haines)'],
      ['Chinik Eskimo Community (Golovin)', 'Chinik Eskimo Community (Golovin)'],
      ['Chippewa Indians of the Bad River', 'Chippewa Indians of the Bad River'],
      ['Chippewa-Cree Indians', 'Chippewa-Cree Indians'],
      ['Chitimacha Tribe of Louisiana', 'Chitimacha Tribe of Louisiana'],
      ['Choctaw Nation of Oklahoma', 'Choctaw Nation of Oklahoma'],
      ['Chuloonawick Native Village', 'Chuloonawick Native Village'],
      ['Circle Native Community', 'Circle Native Community'],
      ['Citizen Band Potawatomi Tribe of Oklahoma', 'Citizen Band Potawatomi Tribe of Oklahoma'],
      ['Cloverdale Rancheria of Pomo Indians', 'Cloverdale Rancheria of Pomo Indians'],
      ['Coast Indian Community of Yurok Indians', 'Coast Indian Community of Yurok Indians'],
      ['Cocopah Tribe of Arizona', 'Cocopah Tribe of Arizona'],
      ['Coeur D&#39;Alene Tribe', 'Coeur D&#39;Alene Tribe'],
      ['Cold Springs Rancheria of Mono I', 'Cold Springs Rancheria of Mono I'],
      ['Colorado River Indian Tribes', 'Colorado River Indian Tribes'],
      ['Comanche Indian Tribe,', 'Comanche Indian Tribe,'],
      ['Confederated Salish &amp; Kootenai Tribes', 'Confederated Salish &amp; Kootenai Tribes'],
      ['Confederated Tribes and Bands of the Yakama Indian', 'Confederated Tribes and Bands of the Yakama Indian'],
      ['Confederated Tribes of the Chehalis', 'Confederated Tribes of the Chehalis'],
      ['Confederated Tribes of the Colville', 'Confederated Tribes of the Colville'],
      ['Confederated Tribes of the Coos', 'Confederated Tribes of the Coos'],
      ['Confederated Tribes of the Goshute', 'Confederated Tribes of the Goshute'],
      ['Confederated Tribes of the Grand Ronde', 'Confederated Tribes of the Grand Ronde'],
      ['Confederated Tribes of the Siletz Reservation', 'Confederated Tribes of the Siletz Reservation'],
      ['Confederated Tribes of the Umatilla Reservation', 'Confederated Tribes of the Umatilla Reservation'],
      ['Confederated Tribes of the Warm Springs', 'Confederated Tribes of the Warm Springs'],
      ['Coquille Tribe of Oregon', 'Coquille Tribe of Oregon'],
      ['Cortina Indian Rancheria of Wintun', 'Cortina Indian Rancheria of Wintun'],
      ['Coushatta Tribe of Louisiana', 'Coushatta Tribe of Louisiana'],
      ['Cow Creek Band of Umpqua Indians', 'Cow Creek Band of Umpqua Indians'],
      ['Cowlitz Indian Tribe', 'Cowlitz Indian Tribe'],
      ['Coyote Valley Band of Pomo Indians', 'Coyote Valley Band of Pomo Indians'],
      ['Craig Community Association', 'Craig Community Association'],
      ['Crow Creek Sioux Tribe', 'Crow Creek Sioux Tribe'],
      ['Crow Tribe of Montana', 'Crow Tribe of Montana'],
      ['Cuyapaipe Community of Diegueno Mission', 'Cuyapaipe Community of Diegueno Mission'],
      ['Death Valley Timbi-Sha Shoshone', 'Death Valley Timbi-Sha Shoshone'],
      ['Delaware Tribe of Indians, Oklahoma', 'Delaware Tribe of Indians, Oklahoma'],
      ['Delaware Tribe of Western Oklahoma', 'Delaware Tribe of Western Oklahoma'],
      ['Devils Lake Sioux Tribe of the Devils', 'Devils Lake Sioux Tribe of the Devils'],
      ['Douglas Indian Association', 'Douglas Indian Association'],
      ['Dry Creek Rancheria of Pomo Indians', 'Dry Creek Rancheria of Pomo Indians'],
      ['Duckwater Shoshone Tribe', 'Duckwater Shoshone Tribe'],
      ['Eastern Band of Cherokee', 'Eastern Band of Cherokee'],
      ['Eastern Shawnee Tribe', 'Eastern Shawnee Tribe'],
      ['Eastern Shoshone Tribe', 'Eastern Shoshone Tribe'],
      ['Echota Cherokee Tribe of Alabama', 'Echota Cherokee Tribe of Alabama'],
      ['Egegik Village', 'Egegik Village'],
      ['Eklutna Native Village', 'Eklutna Native Village'],
      ['Ekwok Village', 'Ekwok Village'],
      ['Elem Indian Colony of Pomo Indians', 'Elem Indian Colony of Pomo Indians'],
      ['Elk Valley Rancheria', 'Elk Valley Rancheria'],
      ['Ely Shoshone Tribe', 'Ely Shoshone Tribe'],
      ['Emmonak Village', 'Emmonak Village'],
      ['Enterprise Rancheria of Maidu', 'Enterprise Rancheria of Maidu'],
      ['Ermineskin Cree Nation', 'Ermineskin Cree Nation'],
      ['Evansville Village (aka Bettles Field)', 'Evansville Village (aka Bettles Field)'],
      ['Fallon Paiute Shoshone Tribe', 'Fallon Paiute Shoshone Tribe'],
      ['FIandreau Santee Sioux Tribe', 'FIandreau Santee Sioux Tribe'],
      ['Fond du Lac Band of Lake Superior Chippewa', 'Fond du Lac Band of Lake Superior Chippewa'],
      ['Forest County Potawatomi', 'Forest County Potawatomi'],
      ['Fort Belknap Indian Community', 'Fort Belknap Indian Community'],
      ['Fort Bidwell Indian Community', 'Fort Bidwell Indian Community'],
      ['Fort Independence Indian Community', 'Fort Independence Indian Community'],
      ['Fort McDermitt Paiute and Shoshone Tribes', 'Fort McDermitt Paiute and Shoshone Tribes'],
      ['Fort McDowell Mojave-Apache Indian Community', 'Fort McDowell Mojave-Apache Indian Community'],
      ['Fort Mojave Indian Tribe of Arizona', 'Fort Mojave Indian Tribe of Arizona'],
      ['Fort Sill Apache Tribe of Oklahoma', 'Fort Sill Apache Tribe of Oklahoma'],
      ['Galena Village (aka Louden Village)', 'Galena Village (aka Louden Village)'],
      ['Gila River Pima-Maricopa Indian Community', 'Gila River Pima-Maricopa Indian Community'],
      ['Grand Traverse Band of Ottawa &amp; Chippewa', 'Grand Traverse Band of Ottawa &amp; Chippewa'],
      ['Greenville Rancheria of Maidu Indians', 'Greenville Rancheria of Maidu Indians'],
      ['Grindtone Indian Rancheria', 'Grindtone Indian Rancheria'],
      ['Guidiville Rancheria of California', 'Guidiville Rancheria of California'],
      ['Gulkana Village', 'Gulkana Village'],
      ['Haliwa-Saponi Indian  Tribe', 'Haliwa-Saponi Indian  Tribe'],
      ['Hannahville Indian Community', 'Hannahville Indian Community'],
      ['Havasupai Tribe', 'Havasupai Tribe'],
      ['Healy Lake Village', 'Healy Lake Village'],
      ['Ho-Chunk Nation', 'Ho-Chunk Nation'],
      ['Hoh Indian Tribe', 'Hoh Indian Tribe'],
      ['Holy Cross Village', 'Holy Cross Village'],
      ['Hoonah Indian Association', 'Hoonah Indian Association'],
      ['Hoopa Valley Tribe', 'Hoopa Valley Tribe'],
      ['Hopi Tribe of Arizona', 'Hopi Tribe of Arizona'],
      ['Hopland Band of Pomo Indians', 'Hopland Band of Pomo Indians'],
      ['Houlton Band of Maliseet Indians', 'Houlton Band of Maliseet Indians'],
      ['Hualapai Indian Tribe', 'Hualapai Indian Tribe'],
      ['Hughes Village', 'Hughes Village'],
      ['Huron Potawatomi, Inc., Michigan', 'Huron Potawatomi, Inc., Michigan'],
      ['Huslia Village', 'Huslia Village'],
      ['Hydaburg Cooperative Association', 'Hydaburg Cooperative Association'],
      ['Igiugig Village', 'Igiugig Village'],
      ['Inaja Band of Diegueno Mission Indians', 'Inaja Band of Diegueno Mission Indians'],
      ['Inupiat Community of the Arctic Slope', 'Inupiat Community of the Arctic Slope'],
      ['Iowa Tribe of Kansas and Nebraska', 'Iowa Tribe of Kansas and Nebraska'],
      ['Iowa Tribe of Oklahoma', 'Iowa Tribe of Oklahoma'],
      ['Ivanoff Bay Village', 'Ivanoff Bay Village'],
      ['Jackson Rancheria of Me-Wuk Indians', 'Jackson Rancheria of Me-Wuk Indians'],
      ['Jamestown Klallam Tribe', 'Jamestown Klallam Tribe'],
      ['Jamul Indian Village', 'Jamul Indian Village'],
      ['Jatibonicu Taino Tribal Nation', 'Jatibonicu Taino Tribal Nation'],
      ['Jena Band of Choctaw Indians', 'Jena Band of Choctaw Indians'],
      ['Jicarilla Apache Tribe', 'Jicarilla Apache Tribe'],
      ['Kaguyak Village', 'Kaguyak Village'],
      ['Kaibab Band of Paiute Indians', 'Kaibab Band of Paiute Indians'],
      ['Kaktovik Village (aka Barter Island)', 'Kaktovik Village (aka Barter Island)'],
      ['Kalispel Indian Community', 'Kalispel Indian Community'],
      ['Karuk Tribe of California', 'Karuk Tribe of California'],
      ['Kashia Band of Pomo Indians', 'Kashia Band of Pomo Indians'],
      ['Kaw Nation, Oklahoma', 'Kaw Nation, Oklahoma'],
      ['Kenaitze Indian Tribe', 'Kenaitze Indian Tribe'],
      ['Ketchikan Indian Corporation', 'Ketchikan Indian Corporation'],
      ['Kewa Pueblo', 'Kewa Pueblo'],
      ['Keweenaw Bay Indian Community', 'Keweenaw Bay Indian Community'],
      ['Kialegee Tribal Town of the Creek', 'Kialegee Tribal Town of the Creek'],
      ['Kickapoo Traditional Tribe of Texas', 'Kickapoo Traditional Tribe of Texas'],
      ['Kickapoo Tribe of Indians', 'Kickapoo Tribe of Indians'],
      ['Kickapoo Tribe of Oklahoma', 'Kickapoo Tribe of Oklahoma'],
      ['King Island Native Community', 'King Island Native Community'],
      ['Kiowa Indian Tribe of Oklahoma', 'Kiowa Indian Tribe of Oklahoma'],
      ['Klamath Indian Tribe of Oregon', 'Klamath Indian Tribe of Oregon'],
      ['Klawock Cooperative Association', 'Klawock Cooperative Association'],
      ['Knik Tribe', 'Knik Tribe'],
      ['Kokhanok Village', 'Kokhanok Village'],
      ['Koliganek Village', 'Koliganek Village'],
      ['Kootenai Tribe of Idaho', 'Kootenai Tribe of Idaho'],
      ['Koyukuk Native Village', 'Koyukuk Native Village'],
      ['La Courte Oreilles Band of Lake Superior Chippewa', 'La Courte Oreilles Band of Lake Superior Chippewa'],
      ['La Jolla Band of Luiseno Mission Indians', 'La Jolla Band of Luiseno Mission Indians'],
      ['La Posta Band of Diegueno Mission Indians', 'La Posta Band of Diegueno Mission Indians'],
      ['Lac du Flambeau Band of Lake Superior Chippewa lndians', 'Lac du Flambeau Band of Lake Superior Chippewa lndians'],
      ['Lac Vieux Desert Band', 'Lac Vieux Desert Band'],
      ['Lakota Sioux Tribe', 'Lakota Sioux Tribe'],
      ['Las Vegas Tribe of Paiute Indians', 'Las Vegas Tribe of Paiute Indians'],
      ['Leech Lake Band Of Ojibwe', 'Leech Lake Band Of Ojibwe'],
      ['Lesnoi Village (aka Woody Island)', 'Lesnoi Village (aka Woody Island)'],
      ['Levelock Village', 'Levelock Village'],
      ['Lime Village', 'Lime Village'],
      ['Little River Band of Ottawa Indians', 'Little River Band of Ottawa Indians'],
      ['Little Traverse Bay Bands of Ottawa Indians', 'Little Traverse Bay Bands of Ottawa Indians'],
      ['Los Coyotes Band of Cahuilla Mission Indians', 'Los Coyotes Band of Cahuilla Mission Indians'],
      ['Lovelock Paiute Tribe of the Lovelock Indian', 'Lovelock Paiute Tribe of the Lovelock Indian'],
      ['Lower Brule Sioux Tribe', 'Lower Brule Sioux Tribe'],
      ['Lower Elwha Tribal Community', 'Lower Elwha Tribal Community'],
      ['Lower Sioux Indian Community', 'Lower Sioux Indian Community'],
      ['Lummi Tribe of the Lummi Reservation', 'Lummi Tribe of the Lummi Reservation'],
      ['Lytton Rancheria of California', 'Lytton Rancheria of California'],
      ['Makah Indian Tribe', 'Makah Indian Tribe'],
      ['Mananita Band of Diegueno Mission', 'Mananita Band of Diegueno Mission'],
      ['Manchester Band of Pomo Indians', 'Manchester Band of Pomo Indians'],
      ['Manley Hot Springs Village', 'Manley Hot Springs Village'],
      ['Manokotak Village', 'Manokotak Village'],
      ['Marie Band of Chippewa Indians', 'Marie Band of Chippewa Indians'],
      ['Mashantucket Pequot Tribe', 'Mashantucket Pequot Tribe'],
      ['McGrath Native Village', 'McGrath Native Village'],
      ['Mdewakanton Sioux Indians', 'Mdewakanton Sioux Indians'],
      ['Mechoopda Indian Tribe', 'Mechoopda Indian Tribe'],
      ['Meherrin Indian Tribe', 'Meherrin Indian Tribe'],
      ['Menominee Indian Tribe of Wisconsin', 'Menominee Indian Tribe of Wisconsin'],
      ['Mentasta Lake Village', 'Mentasta Lake Village'],
      ['Mesa Grande Band of Diegueno Mission Indians', 'Mesa Grande Band of Diegueno Mission Indians'],
      ['Mescalero Apache Tribe of the Mescalero', 'Mescalero Apache Tribe of the Mescalero'],
      ['Metis Nation of Ontario', 'Metis Nation of Ontario'],
      ['Metlakatla Indian Community', 'Metlakatla Indian Community'],
      ['Miami Tribe of Oklahoma', 'Miami Tribe of Oklahoma'],
      ['Miccosukee Tribe of Indians of Florida', 'Miccosukee Tribe of Indians of Florida'],
      ['Middletown Rancheria of Pomo Indians of California', 'Middletown Rancheria of Pomo Indians of California'],
      ['Mille Lacs Band of Ojibwe', 'Mille Lacs Band of Ojibwe'],
      ['Minnesota Chippewa Tribe,', 'Minnesota Chippewa Tribe,'],
      ['Mississippi Band of Choctaw Indians', 'Mississippi Band of Choctaw Indians'],
      ['Moapa Band of Paiute lndians', 'Moapa Band of Paiute lndians'],
      ['Modoc Tribe of Oklahoma', 'Modoc Tribe of Oklahoma'],
      ['Mohegan Indian Tribe', 'Mohegan Indian Tribe'],
      ['Mooretown Rancheria of Maidu', 'Mooretown Rancheria of Maidu'],
      ['Morongo Band of Cahuilla Mission', 'Morongo Band of Cahuilla Mission'],
      ['Muckleshoot Indian Tribe', 'Muckleshoot Indian Tribe'],
      ['Muscogee ( Creek ) Nation', 'Muscogee ( Creek ) Nation'],
      ['Naknek Native Village', 'Naknek Native Village'],
      ['Narragansett Indian Tribe', 'Narragansett Indian Tribe'],
      ['Native Hawaiian', 'Native Hawaiian'],
      ['Native Village of Akhiok', 'Native Village of Akhiok'],
      ['Native Village of Akutan', 'Native Village of Akutan'],
      ['Native Village of Aleknagik', 'Native Village of Aleknagik'],
      ['Native Village of Ambler', 'Native Village of Ambler'],
      ['Native Village of Atka', 'Native Village of Atka'],
      ['Native Village of Barrow', 'Native Village of Barrow'],
      ['Native Village of Belkofski', 'Native Village of Belkofski'],
      ['Native Village of Brevig Mission', 'Native Village of Brevig Mission'],
      ['Native Village of Buckland', 'Native Village of Buckland'],
      ['Native Village of Cantwell', 'Native Village of Cantwell'],
      ['Native Village of Chanega (aka Chenega)', 'Native Village of Chanega (aka Chenega)'],
      ['Native Village of Chignik', 'Native Village of Chignik'],
      ['Native Village of Chignik Lagoon', 'Native Village of Chignik Lagoon'],
      ['Native Village of Chistochina', 'Native Village of Chistochina'],
      ['Native Village of Chitina', 'Native Village of Chitina'],
      ['Native Village of Chuatbaluk (Russian Mission, Kuskokwim)', 'Native Village of Chuatbaluk (Russian Mission, Kuskokwim)'],
      ['Native Village of Council', 'Native Village of Council'],
      ['Native Village of Deering', 'Native Village of Deering'],
      ['Native Village of Dillingham', 'Native Village of Dillingham'],
      ['Native Village of Diomede (aka Inalik)', 'Native Village of Diomede (aka Inalik)'],
      ['Native Village of Eagle', 'Native Village of Eagle'],
      ['Native Village of Eek', 'Native Village of Eek'],
      ['Native Village of Ekuk', 'Native Village of Ekuk'],
      ['Native Village of Elim', 'Native Village of Elim'],
      ['Native Village of Eyak (Cordova)', 'Native Village of Eyak (Cordova)'],
      ['Native Village of False Pass', 'Native Village of False Pass'],
      ['Native Village of Fort Yukon', 'Native Village of Fort Yukon'],
      ['Native Village of Gakona', 'Native Village of Gakona'],
      ['Native Village of Gambell', 'Native Village of Gambell'],
      ['Native Village of Georgetown', 'Native Village of Georgetown'],
      ['Native Village of Goodnews Bay', 'Native Village of Goodnews Bay'],
      ['Native Village of Hamilton', 'Native Village of Hamilton'],
      ['Native Village of Hooper Bay', 'Native Village of Hooper Bay'],
      ['Native Village of Kanatak', 'Native Village of Kanatak'],
      ['Native Village of Karluk', 'Native Village of Karluk'],
      ['Native Village of Kasigluk', 'Native Village of Kasigluk'],
      ['Native Village of Kiana', 'Native Village of Kiana'],
      ['Native Village of Kipnuk', 'Native Village of Kipnuk'],
      ['Native Village of Kivalina', 'Native Village of Kivalina'],
      ['Native Village of Kluti Kaah (aka Copper Center)', 'Native Village of Kluti Kaah (aka Copper Center)'],
      ['Native Village of Kobuk', 'Native Village of Kobuk'],
      ['Native Village of Kongiganak', 'Native Village of Kongiganak'],
      ['Native Village of Kotzebue', 'Native Village of Kotzebue'],
      ['Native Village of Koyuk', 'Native Village of Koyuk'],
      ['Native Village of Kwigillingok', 'Native Village of Kwigillingok'],
      ['Native Village of Kwinhagak (aka Quinhagak)', 'Native Village of Kwinhagak (aka Quinhagak)'],
      ['Native Village of Larsen Bay', 'Native Village of Larsen Bay'],
      ['Native Village of Marshall (aka Fortuna Ledge)', 'Native Village of Marshall (aka Fortuna Ledge)'],
      ['Native Village of Mary&#39;s Igloo', 'Native Village of Mary&#39;s Igloo'],
      ['Native Village of Mekoryuk', 'Native Village of Mekoryuk'],
      ['Native Village of Minto', 'Native Village of Minto'],
      ['Native Village of Mountain Village', 'Native Village of Mountain Village'],
      ['Native Village of Nanwalek (aka English Bay)', 'Native Village of Nanwalek (aka English Bay)'],
      ['Native Village of Napaimute', 'Native Village of Napaimute'],
      ['Native Village of Napakiak', 'Native Village of Napakiak'],
      ['Native Village of Napaskiak', 'Native Village of Napaskiak'],
      ['Native Village of Nelson Lagoon', 'Native Village of Nelson Lagoon'],
      ['Native Village of Nightmute', 'Native Village of Nightmute'],
      ['Native Village of Nikolski', 'Native Village of Nikolski'],
      ['Native Village of Noatak', 'Native Village of Noatak'],
      ['Native Village of Nuiqsut (aka Nooiksut)', 'Native Village of Nuiqsut (aka Nooiksut)'],
      ['Native Village of Nunapitchuk', 'Native Village of Nunapitchuk'],
      ['Native Village of Ouzinkie', 'Native Village of Ouzinkie'],
      ['Native Village of Paimiut', 'Native Village of Paimiut'],
      ['Native Village of Perryville', 'Native Village of Perryville'],
      ['Native Village of Pilot Point', 'Native Village of Pilot Point'],
      ['Native Village of Pitka&#39;s Point', 'Native Village of Pitka&#39;s Point'],
      ['Native Village of Point Hope', 'Native Village of Point Hope'],
      ['Native Village of Point Lay', 'Native Village of Point Lay'],
      ['Native Village of Port Graham', 'Native Village of Port Graham'],
      ['Native Village of Port Heiden', 'Native Village of Port Heiden'],
      ['Native Village of Port Lions', 'Native Village of Port Lions'],
      ['Native Village of Ruby', 'Native Village of Ruby'],
      ['Native Village of Russian Mission (Yukon)', 'Native Village of Russian Mission (Yukon)'],
      ['Native Village of Savoonga', 'Native Village of Savoonga'],
      ['Native Village of Scammon Bay', 'Native Village of Scammon Bay'],
      ['Native Village of Selawik', 'Native Village of Selawik'],
      ['Native Village of Shaktoolik', 'Native Village of Shaktoolik'],
      ['Native Village of Sheldon&#39;s Point', 'Native Village of Sheldon&#39;s Point'],
      ['Native Village of Shishmaref', 'Native Village of Shishmaref'],
      ['Native Village of Shungnak', 'Native Village of Shungnak'],
      ['Native Village of Stevens', 'Native Village of Stevens'],
      ['Native Village of Tanacross', 'Native Village of Tanacross'],
      ['Native Village of Tanana', 'Native Village of Tanana'],
      ['Native Village of Tatitek', 'Native Village of Tatitek'],
      ['Native Village of Tazlina', 'Native Village of Tazlina'],
      ['Native Village of Tejin', 'Native Village of Tejin'],
      ['Native Village of Teller', 'Native Village of Teller'],
      ['Native Village of Toksook Bay', 'Native Village of Toksook Bay'],
      ['Native Village of Tonunak', 'Native Village of Tonunak'],
      ['Native Village of Tuntutuliak', 'Native Village of Tuntutuliak'],
      ['Native Village of Tyonek', 'Native Village of Tyonek'],
      ['Native Village of Unalakleet', 'Native Village of Unalakleet'],
      ['Native Village of Unga', 'Native Village of Unga'],
      ['Native Village of Venetie Tribal Government (Arctic Village and Village of Venetie)', 'Native Village of Venetie Tribal Government (Arctic Village and Village of Venetie)'],
      ['Native Village of Wales', 'Native Village of Wales'],
      ['Native Village of White Mountain', 'Native Village of White Mountain'],
      ['Navajo Nation of Arizona', 'Navajo Nation of Arizona'],
      ['Nenana Native Association', 'Nenana Native Association'],
      ['New Stuyahok Village', 'New Stuyahok Village'],
      ['Newhalen Village', 'Newhalen Village'],
      ['Newtok Village', 'Newtok Village'],
      ['Nez Perce Tribe of Idaho', 'Nez Perce Tribe of Idaho'],
      ['Nikolai Village', 'Nikolai Village'],
      ['Ninilchik Village', 'Ninilchik Village'],
      ['Nisqually Indian Tribe', 'Nisqually Indian Tribe'],
      ['Nome Eskimo Community', 'Nome Eskimo Community'],
      ['Nondalton Village', 'Nondalton Village'],
      ['Nooksack Indian Tribe of Washington', 'Nooksack Indian Tribe of Washington'],
      ['Noorvik Native Community', 'Noorvik Native Community'],
      ['North Fork Rancheria of Mono Indians of California', 'North Fork Rancheria of Mono Indians of California'],
      ['Northern Cheyenne Tribe', 'Northern Cheyenne Tribe'],
      ['Northfork Rancheria of Mono', 'Northfork Rancheria of Mono'],
      ['Northway Village', 'Northway Village'],
      ['Northwestern Band of Shoshoni', 'Northwestern Band of Shoshoni'],
      ['Nulato Village', 'Nulato Village'],
      ['Oglala Sioux Tribe of the Pine Ridge', 'Oglala Sioux Tribe of the Pine Ridge'],
      ['Ohkay Owingeh Pueblo', 'Ohkay Owingeh Pueblo'],
      ['Omaha Tribe of Nebraska', 'Omaha Tribe of Nebraska'],
      ['Oneida Nation of New York', 'Oneida Nation of New York'],
      ['Oneida Tribe of Wisconsin', 'Oneida Tribe of Wisconsin'],
      ['Onondaga Nation of New York', 'Onondaga Nation of New York'],
      ['Organized Village of Grayling (aka Holikachuk)', 'Organized Village of Grayling (aka Holikachuk)'],
      ['Organized Village of Kake', 'Organized Village of Kake'],
      ['Organized Village of Kasaan', 'Organized Village of Kasaan'],
      ['Organized Village of Kwethluk', 'Organized Village of Kwethluk'],
      ['Organized Village of Saxman', 'Organized Village of Saxman'],
      ['Orutsararmuit Native Village (aka Bethel)', 'Orutsararmuit Native Village (aka Bethel)'],
      ['Osage Nation of Oklahoma', 'Osage Nation of Oklahoma'],
      ['Oscarville Traditional Village', 'Oscarville Traditional Village'],
      ['Otoe-Missouria Tribe of Indians, Oklahoma', 'Otoe-Missouria Tribe of Indians, Oklahoma'],
      ['Ottawa Tribe of Oklahoma', 'Ottawa Tribe of Oklahoma'],
      ['Paiute Indian Tribe of Utah', 'Paiute Indian Tribe of Utah'],
      ['Paiute-Shoshone Indians', 'Paiute-Shoshone Indians'],
      ['Paiute-Shoshone lndians', 'Paiute-Shoshone lndians'],
      ['Paiute-Shoshone Tribe', 'Paiute-Shoshone Tribe'],
      ['Pala Band of Luiseno Mission', 'Pala Band of Luiseno Mission'],
      ['Pascua Yaqui Tribe of Arizona', 'Pascua Yaqui Tribe of Arizona'],
      ['Paskenta Band of Nomlaki Indians', 'Paskenta Band of Nomlaki Indians'],
      ['Passamaquoddy Tribe of Maine', 'Passamaquoddy Tribe of Maine'],
      ['Paul of Harbor Village', 'Paul of Harbor Village'],
      ['Pauma Band of Luiseno Mission', 'Pauma Band of Luiseno Mission'],
      ['Pawnee Indian Tribe of Oklahoma', 'Pawnee Indian Tribe of Oklahoma'],
      ['Pechanga Band of Luiseno Mission', 'Pechanga Band of Luiseno Mission'],
      ['Pedro Bay Village', 'Pedro Bay Village'],
      ['Penobscot Tribe of Maine,', 'Penobscot Tribe of Maine,'],
      ['Peoria Tribe of Indians of Oklahoma', 'Peoria Tribe of Indians of Oklahoma'],
      ['Petersburg Indian Association', 'Petersburg Indian Association'],
      ['Picayune Rancheria of Chukchansi', 'Picayune Rancheria of Chukchansi'],
      ['Piikani Nation Canada', 'Piikani Nation Canada'],
      ['Pilot Station Traditional Village', 'Pilot Station Traditional Village'],
      ['Pinoleville Rancheria of Pomo', 'Pinoleville Rancheria of Pomo'],
      ['Pit River Tribe of California', 'Pit River Tribe of California'],
      ['Plains Cree Canada', 'Plains Cree Canada'],
      ['Platinum Traditional Village', 'Platinum Traditional Village'],
      ['Poarch Band of Creek Indians', 'Poarch Band of Creek Indians'],
      ['Pokagon Band of Potawatomi', 'Pokagon Band of Potawatomi'],
      ['Ponca Tribe of lndians of Oklahoma', 'Ponca Tribe of lndians of Oklahoma'],
      ['Ponca Tribe of Nebraska', 'Ponca Tribe of Nebraska'],
      ['Port Gamble Indian Community', 'Port Gamble Indian Community'],
      ['Portage Creek Village (aka Ohgsenakale)', 'Portage Creek Village (aka Ohgsenakale)'],
      ['Potter Valley Rancheria', 'Potter Valley Rancheria'],
      ['Prairie Band of Potawatomi', 'Prairie Band of Potawatomi'],
      ['Prairie Island Indian', 'Prairie Island Indian'],
      ['Pribil of Islands Aleut Communities of St. Paul &amp; St. George Islands', 'Pribil of Islands Aleut Communities of St. Paul &amp; St. George Islands'],
      ['Pueblo of Acoma, New Mexico', 'Pueblo of Acoma, New Mexico'],
      ['Pueblo of Cochiti, New Mexico', 'Pueblo of Cochiti, New Mexico'],
      ['Pueblo of Isleta, New Mexico', 'Pueblo of Isleta, New Mexico'],
      ['Pueblo of Jemez, New Mexico', 'Pueblo of Jemez, New Mexico'],
      ['Pueblo of Laguna, New Mexico', 'Pueblo of Laguna, New Mexico'],
      ['Pueblo of Nambe, New Mexico', 'Pueblo of Nambe, New Mexico'],
      ['Pueblo of Picuris, New Mexico', 'Pueblo of Picuris, New Mexico'],
      ['Pueblo of Pojoaque, New Mexico', 'Pueblo of Pojoaque, New Mexico'],
      ['Pueblo of San Felipe, New Mexico', 'Pueblo of San Felipe, New Mexico'],
      ['Pueblo of San Ildefonso, New Mexico', 'Pueblo of San Ildefonso, New Mexico'],
      ['Pueblo of San Juan, New Mexico', 'Pueblo of San Juan, New Mexico'],
      ['Pueblo of Sandia, New Mexico', 'Pueblo of Sandia, New Mexico'],
      ['Pueblo of Santa Ana, New Mexico', 'Pueblo of Santa Ana, New Mexico'],
      ['Pueblo of Santa Clara, New Mexico', 'Pueblo of Santa Clara, New Mexico'],
      ['Pueblo of Santo Domingo, New Mexico', 'Pueblo of Santo Domingo, New Mexico'],
      ['Pueblo of Taos, New Mexico', 'Pueblo of Taos, New Mexico'],
      ['Pueblo of Tesuque, New Mexico', 'Pueblo of Tesuque, New Mexico'],
      ['Pueblo of Zia, New Mexico', 'Pueblo of Zia, New Mexico'],
      ['Puyallup Tribe of the Puyallup', 'Puyallup Tribe of the Puyallup'],
      ['Pyramid Lake Paiute Tribe', 'Pyramid Lake Paiute Tribe'],
      ['Qagan Toyagungin Tribe of Sand Point Village', 'Qagan Toyagungin Tribe of Sand Point Village'],
      ['Qawalingin Tribe of Unalaska', 'Qawalingin Tribe of Unalaska'],
      ['Quapaw Tribe of Oklahoma', 'Quapaw Tribe of Oklahoma'],
      ['Quartz Valley', 'Quartz Valley'],
      ['Quechan Tribe', 'Quechan Tribe'],
      ['Quileute Tribe', 'Quileute Tribe'],
      ['Quinault Tribe', 'Quinault Tribe'],
      ['Ramona Band or Village', 'Ramona Band or Village'],
      ['Rampart Village', 'Rampart Village'],
      ['Red Cliff Band of Lake Superior Chippewa', 'Red Cliff Band of Lake Superior Chippewa'],
      ['Red Lake Band of Chippewa Indians', 'Red Lake Band of Chippewa Indians'],
      ['Redding Rancheria of California', 'Redding Rancheria of California'],
      ['Redwood Valley Rancheria of Pomo', 'Redwood Valley Rancheria of Pomo'],
      ['Reno-Sparks Indian Colony, Nevada', 'Reno-Sparks Indian Colony, Nevada'],
      ['Rincon Band of Luiseno Mission lndians', 'Rincon Band of Luiseno Mission lndians'],
      ['Robinson Rancheria of Pomo', 'Robinson Rancheria of Pomo'],
      ['Rosebud Sioux Tribe of the Rosebud', 'Rosebud Sioux Tribe of the Rosebud'],
      ['Round Valley lndian Tribes', 'Round Valley lndian Tribes'],
      ['Rumsey Indian Rancheria of Wintun', 'Rumsey Indian Rancheria of Wintun'],
      ['Sac &amp; Fox Nation of Missouri in Kansas', 'Sac &amp; Fox Nation of Missouri in Kansas'],
      ['Sac &amp; Fox Nation, Oklahoma', 'Sac &amp; Fox Nation, Oklahoma'],
      ['Sac &amp; Fox Tribe of the Mississippi in Iowa', 'Sac &amp; Fox Tribe of the Mississippi in Iowa'],
      ['Saddle Lake Cree Nation Canada', 'Saddle Lake Cree Nation Canada'],
      ['Saginaw Chippewa lndian', 'Saginaw Chippewa lndian'],
      ['Saint George (See Pribil of Islands Aleut Communities of St. Paul &amp; St. George Islands)', 'Saint George (See Pribil of Islands Aleut Communities of St. Paul &amp; St. George Islands)'],
      ['Salt River Pima Maricopa Indian', 'Salt River Pima Maricopa Indian'],
      ['Salt River Pima-Maricopa Indian Community', 'Salt River Pima-Maricopa Indian Community'],
      ['Samish Indian Tribe', 'Samish Indian Tribe'],
      ['Samson Cree Nation', 'Samson Cree Nation'],
      ['San Carlos Apache', 'San Carlos Apache'],
      ['San Juan Southern Paiute Tribe of Arizona,', 'San Juan Southern Paiute Tribe of Arizona,'],
      ['San Manuel Band of Mission Indians', 'San Manuel Band of Mission Indians'],
      ['San Pascual Band of Diegueno', 'San Pascual Band of Diegueno'],
      ['Santa Rosa Band of Cahuiila Mission', 'Santa Rosa Band of Cahuiila Mission'],
      ['Santa Rosa lndian Community', 'Santa Rosa lndian Community'],
      ['Santa Ynez Band of Chumash Mission', 'Santa Ynez Band of Chumash Mission'],
      ['Santa Ysabel Band of Diegueno Mission', 'Santa Ysabel Band of Diegueno Mission'],
      ['Santee Sioux Tribe', 'Santee Sioux Tribe'],
      ['Sauk-Suiattle Indian Tribe', 'Sauk-Suiattle Indian Tribe'],
      ['Sault Ste. Marie Tribe of Chippewa', 'Sault Ste. Marie Tribe of Chippewa'],
      ['Scotts Valley Band of Pomo', 'Scotts Valley Band of Pomo'],
      ['Seldovia Native Village', 'Seldovia Native Village'],
      ['Seminole Nation of Oklahoma', 'Seminole Nation of Oklahoma'],
      ['Seminole Tribe of Florida', 'Seminole Tribe of Florida'],
      ['Seneca Nation of New York', 'Seneca Nation of New York'],
      ['Seneca-Cayuga Tribe of Oklahoma', 'Seneca-Cayuga Tribe of Oklahoma'],
      ['Shageluk Native Village', 'Shageluk Native Village'],
      ['Shakopee Mdewakanton Sioux', 'Shakopee Mdewakanton Sioux'],
      ['Sheep Ranch Rancheria of Me-Wttk', 'Sheep Ranch Rancheria of Me-Wttk'],
      ['Sherwood Valley Rancheria of Pomo Indians', 'Sherwood Valley Rancheria of Pomo Indians'],
      ['Shingle Springs Band of Miwok Indians', 'Shingle Springs Band of Miwok Indians'],
      ['Shoalwater Bay Tribe', 'Shoalwater Bay Tribe'],
      ['Shoshone Tribe', 'Shoshone Tribe'],
      ['Shoshone-Bannock Tribes', 'Shoshone-Bannock Tribes'],
      ['Shoshone-Paiute Tribes', 'Shoshone-Paiute Tribes'],
      ['Siksika Nation', 'Siksika Nation'],
      ['Sisseton-Wahpeton Sioux Tribe', 'Sisseton-Wahpeton Sioux Tribe'],
      ['Sitka Tribe of Alaska', 'Sitka Tribe of Alaska'],
      ['Skagway Village', 'Skagway Village'],
      ['Skawahlook First Nation Canada', 'Skawahlook First Nation Canada'],
      ['Skokomish Indian Tribe', 'Skokomish Indian Tribe'],
      ['Skull Valley Band of Goshute', 'Skull Valley Band of Goshute'],
      ['Smith River Rancheria', 'Smith River Rancheria'],
      ['Snoqualmie Tribe', 'Snoqualmie Tribe'],
      ['Soboba Band of Luiseno Mission', 'Soboba Band of Luiseno Mission'],
      ['Sokaogon Chippewa Community', 'Sokaogon Chippewa Community'],
      ['South Naknek Village', 'South Naknek Village'],
      ['Southern Ute lndian Tribe', 'Southern Ute lndian Tribe'],
      ['Spirit Lake Tribe', 'Spirit Lake Tribe'],
      ['Spokane Tribe', 'Spokane Tribe'],
      ['Squaxin Island Tribe', 'Squaxin Island Tribe'],
      ['St. Croix Chippewa Indians', 'St. Croix Chippewa Indians'],
      ['St. Regis Mohawk Tribe', 'St. Regis Mohawk Tribe'],
      ['Standing Rock Sioux Tribe', 'Standing Rock Sioux Tribe'],
      ['Stebbins Community Association', 'Stebbins Community Association'],
      ['Stillaguamish Tribe', 'Stillaguamish Tribe'],
      ['Stockbridge-Munsee Community', 'Stockbridge-Munsee Community'],
      ['Summit Lake Paiute Tribe', 'Summit Lake Paiute Tribe'],
      ['Suquamish lndian Tribe', 'Suquamish lndian Tribe'],
      ['Susanville Indian Rancheria of Paiute', 'Susanville Indian Rancheria of Paiute'],
      ['Swinomish Indians', 'Swinomish Indians'],
      ['Sycuan Band of Diegueno Mission', 'Sycuan Band of Diegueno Mission'],
      ['Table Bluff Rancheria of Wiyot', 'Table Bluff Rancheria of Wiyot'],
      ['Table Mountain Rancheria', 'Table Mountain Rancheria'],
      ['Tachi Yokut Tribe', 'Tachi Yokut Tribe'],
      ['Takotna Village', 'Takotna Village'],
      ['Telida Village', 'Telida Village'],
      ['Te-Moak Tribes of Western Shoshone', 'Te-Moak Tribes of Western Shoshone'],
      ['Thlopthlocco Tribal Town of the Creek', 'Thlopthlocco Tribal Town of the Creek'],
      ['Three Affiliated Tribes', 'Three Affiliated Tribes'],
      ['Tohono O&#39;odham Nation of Arizona', 'Tohono O&#39;odham Nation of Arizona'],
      ['Tonawanda Band of Seneca Indians', 'Tonawanda Band of Seneca Indians'],
      ['Tonkawa Tribe of Indians of Oklahoma', 'Tonkawa Tribe of Indians of Oklahoma'],
      ['Tonto Apache Tribe of Arizona', 'Tonto Apache Tribe of Arizona'],
      ['Torres-Martinez Band of Cahuilla', 'Torres-Martinez Band of Cahuilla'],
      ['Traditional Village of Togiak', 'Traditional Village of Togiak'],
      ['Tulalip Tribes of the Tulalip Reservation,', 'Tulalip Tribes of the Tulalip Reservation,'],
      ['Tule River Indian Tribe', 'Tule River Indian Tribe'],
      ['Tuluksak Native Community', 'Tuluksak Native Community'],
      ['Tunica-Biloxi Indian Tribe', 'Tunica-Biloxi Indian Tribe'],
      ['Tuolumne Band of Me-Wuk Indians', 'Tuolumne Band of Me-Wuk Indians'],
      ['Turtle Mountain Band of Chippewa Indians', 'Turtle Mountain Band of Chippewa Indians'],
      ['Tuscarora Nation of New York', 'Tuscarora Nation of New York'],
      ['Twenty-Nine Palms Band', 'Twenty-Nine Palms Band'],
      ['Twin Hills Village', 'Twin Hills Village'],
      ['Ugashik Village', 'Ugashik Village'],
      ['Umkumiute Native Village', 'Umkumiute Native Village'],
      ['United Auburn Indian', 'United Auburn Indian'],
      ['United Cherokee Nation', 'United Cherokee Nation'],
      ['United Houma Nation', 'United Houma Nation'],
      ['United Keetoowah Band', 'United Keetoowah Band'],
      ['Upper Lake Band of Pomo', 'Upper Lake Band of Pomo'],
      ['Upper Sioux Indian Community', 'Upper Sioux Indian Community'],
      ['Upper Skagit Indian Tribe', 'Upper Skagit Indian Tribe'],
      ['Ute lndian Tribe', 'Ute lndian Tribe'],
      ['Ute Mountain Tribe', 'Ute Mountain Tribe'],
      ['Utu Utu Gwaitu Paiute Tribe', 'Utu Utu Gwaitu Paiute Tribe'],
      ['Viejas (Baron Long) Group&#39; of Capitart Grande Band', 'Viejas (Baron Long) Group&#39; of Capitart Grande Band'],
      ['Vilage of Ohogamiut', 'Vilage of Ohogamiut'],
      ['Village of Afognak', 'Village of Afognak'],
      ['Village of Alakanuk', 'Village of Alakanuk'],
      ['Village of Anaktuvuk Pass', 'Village of Anaktuvuk Pass'],
      ['Village of Aniak', 'Village of Aniak'],
      ['Village of Atmautluak', 'Village of Atmautluak'],
      ['Village of Bill Moore&#39;s Slough', 'Village of Bill Moore&#39;s Slough'],
      ['Village of Chefornak', 'Village of Chefornak'],
      ['Village of Clarks&#39;s Point', 'Village of Clarks&#39;s Point'],
      ['Village of Crooked Creek', 'Village of Crooked Creek'],
      ['Village of Dot Lake', 'Village of Dot Lake'],
      ['Village of Kalskag', 'Village of Kalskag'],
      ['Village of Kaltag', 'Village of Kaltag'],
      ['Village of Kotlik', 'Village of Kotlik'],
      ['Village of Lower Kalskag', 'Village of Lower Kalskag'],
      ['Village of Old Harbor', 'Village of Old Harbor'],
      ['Village of Red Devil', 'Village of Red Devil'],
      ['Village of Salamatoff', 'Village of Salamatoff'],
      ['Village of Sleetmute', 'Village of Sleetmute'],
      ['Village of Solomon', 'Village of Solomon'],
      ['Village of Stony River', 'Village of Stony River'],
      ['Village of Venetie (See Native Village of Venetie Tribal Government)', 'Village of Venetie (See Native Village of Venetie Tribal Government)'],
      ['Village of Wainwright', 'Village of Wainwright'],
      ['Villiage of Iliamna', 'Villiage of Iliamna'],
      ['Walker River Paiute Tribe', 'Walker River Paiute Tribe'],
      ['Walpole Island First Nation Canada', 'Walpole Island First Nation Canada'],
      ['Wampanoag Tribe of Gay Head', 'Wampanoag Tribe of Gay Head'],
      ['Washoe Tribe of Nevada &amp; California', 'Washoe Tribe of Nevada &amp; California'],
      ['Wassamassaw Tribe', 'Wassamassaw Tribe'],
      ['White Earth Band of Chippewa', 'White Earth Band of Chippewa'],
      ['White Mountain Apache', 'White Mountain Apache'],
      ['Wichita and Affiliated Tribes', 'Wichita and Affiliated Tribes'],
      ['Winnebago Tribe', 'Winnebago Tribe'],
      ['Winnemucca Indian', 'Winnemucca Indian'],
      ['Wrangell Cooperative Association', 'Wrangell Cooperative Association'],
      ['Wyandotte Tribe', 'Wyandotte Tribe'],
      ['Yakama Tribe', 'Yakama Tribe'],
      ['Yaltutat Tlingit Tribe', 'Yaltutat Tlingit Tribe'],
      ['Yankton Sioux Tribe', 'Yankton Sioux Tribe'],
      ['Yavapai-Apache Nation', 'Yavapai-Apache Nation'],
      ['Yavapai-Prescott Tribe', 'Yavapai-Prescott Tribe'],
      ['Yerington Paiute Tribe', 'Yerington Paiute Tribe'],
      ['Yomba Shoshone Tribe', 'Yomba Shoshone Tribe'],
      ['Ysleta Del Sur Pueblo of Texas Yurok Tribe', 'Ysleta Del Sur Pueblo of Texas Yurok Tribe'],
      ['Yupiit of Andreafski', 'Yupiit of Andreafski'],
      ['Zuni Tribe', 'Zuni Tribe']
    ]
  end
end